### ISSUE TITLE
@DependencyEndpoint & Never returning closure

### ISSUE THREAD

**Issue by Alex293** [pointfreeco/swift-dependencies#148]
### Description

When applying `@DependencyEndpoint` to a function which return a non-optional type one must provide a closure. While this moved some runtime checks to compile time checks it's not always possible to provide a sensible value or even a value at all.
One can avoid providing a value using `fatalError()` but the macro then emits invalid swift code.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Expected behavior

The macro should emit valid swift code even when using `fatalError()` but I think there should be an option to specify the behaviour of the macro so one can skip writing the fatalError entirely

### Steps to reproduce

```
@DependencyEndpoint
public var fetchCategoryIds: () async throws -> Set<Article.Category.ID> = { fatalError() }
  private var _fetchCategoryIds: () async throws -> Set<Article.Category.ID> = {
      XCTestDynamicOverlay.XCTFail("Unimplemented: 'fetchCategoryIds'")
      return fatalError()
  }
{
    @storageRestrictions(initializes: _fetchCategoryIds)
    init(initialValue) {
        _fetchCategoryIds = initialValue
    }
    get {
        _fetchCategoryIds
    }
    set {
        _fetchCategoryIds = newValue
    }
}
```

### Dependencies version information

1.1.1

**Comment by Alex293** [comment]
Yeah I picked a bad example, I was working on a use case where I can't provide a default and picked something else close. Also while understandable I think it's surprising that optional are special cased in the same way as void.

**Comment by Alex293** [comment]
My main concern here is departing some the interface vs implementation, I'm all in for the closure style but it's strange to provide default that should not be used. Maybe those shouldn't have the @DependencyEndpoint applied when using @DependencyClient and should be added to the init ?

**Comment by stephencelis** [comment]
> Yeah I picked a bad example, I was working on a use case where I can't provide a default and picked something else close. Also while understandable I think it's surprising that optional are special cased in the same way as void.

We could reconsider, but since Swift heavily special cases `Void` and `Optional` in the language we made exceptions for these types. Any example of why it would be better to _not_ special-case optional?

> My main concern here is departing from the interface / implementation idiom, I'm all in for the closure style but it's strange to provide default that should not be used. Maybe those shouldn't have the @DependencyEndpoint applied when using @DependencyClient and should be added to the generated init instead and required then ?

The default _is_ used in tests, though, which is the primary reason to use `@DependencyClient` in the first place. A `fatalError` will crash your entire test suite on failure instead of more gracefully emitting a test failure and continuing.

**Comment by Alex293** [comment]
I guess It feel strange that I must provide some defaults to some methods but not for others, for void methods conceptually we are replacing the whole method so it make sens but choosing nil as default is kinda going a bit to far ? As said, it is a very reasonable choice as this would be the default most people use but then why not special case bool ?

I get that the whole point of this is tests but I'm more confortable having at least a tiny separation between interface code that should be used in test and production and test specific code. It's not about the technicalities but more about being able to make the interface as readable as possible. I think having to provide a testValue was a neat middle ground where test shenanigans were grouped without wrinkling code inside the interface.

On a side note, using the labels is awesome !

**Comment by jshier** [comment]
Is this not where we would use `unimplemented` directly? I've found that `() -> AsyncStream<Value>` can be defaulted to `{ unimplemented() }` for tests. Could the macro do that here?

**Comment by Alex293** [comment]
I didn't tried as using it outside of the closure was raising a warning but that would be great IMHO

**Comment by stephencelis** [comment]
> I guess It feel strange that I must provide some defaults to some methods but not for others, for void methods conceptually we are replacing the whole method so it make sens but choosing nil as default is kinda going a bit to far ? As said, it is a very reasonable choice as this would be the default most people use but then why not special case bool ?

There is only one correct value for `Void`, and Swift even doesn't force you to put `-> Void` on `func`, so we can retain the explicit behavior there.

Optionals are more arguable. We special case because `nil` is a default, implicit assignment for `var foo: Int?`, though this is admittedly different than a function return value. Still, for any optional type we don't know about, `nil` is the one value we can pluck out of thin air.

The reason we don't special case `Bool` is because we had to draw the line somewhere, and right now we've drawn it pretty shortly. `Bool` is different than `Optional`, though, because now there are two values we know about and the library would have to choose. An "empty"-seeming value of `false` might seem appropriate, but `true` is just as fine a default and even preferable in some situations (depending on `&&` vs. `||`). At the end of the day, though, we're just trying to be ergonomic in omitting these defaults, so maybe `Bool.random()` would be fine for a default failure.

And if we special case `Bool` maybe we'd also include numbers and collections...

And then maybe we'd special case `DefaultInitializable` values with a protocol...

All of these are options, but they introduce more questions and require more opinions.

> I get that the whole point of this is tests but I'm more confortable having at least a tiny separation between interface code that should be used in test and production and test specific code. It's not about the technicalities but more about being able to make the interface as readable as possible. I think having to provide a testValue was a neat middle ground where test shenanigans were grouped without wrinkling code inside the interface.

The `Dependencies` library in general straddles the line by declaring that testability is a requirement of the interface. `TestDependencyKey` conformances are required in the module that declares the dependency and cannot be separated out into just the tests, for example.

In the case of these dependency endpoints, the default test value is similarly required at compile time to ensure tests don't crash at runtime.

> That's why I'm wondering about an option for the @DependencyClient macro to require those in init instead of inline.

I'm not quite sure what you mean by this. Can you sketch an example?

**Comment by stephencelis** [comment]
> Is this not where we would use `unimplemented` directly? I've found that `() -> AsyncStream<Value>` can be defaulted to `{ unimplemented() }` for tests. Could the macro do that here?

@jshier We consider `@DependencyClient`/`@DependencyEndpoint` to be a replacement for `unimplemented` that learned a few lessons along the way. In particular, we believe that the `fatalError`s it emitted were a mistake that led to crashing test suites. We consider `@DependencyClient`'s default value diagnostic to be a feature that can help ensure your test suite runs without crashing at compile time.

If anything, even if we do special-case `fatalError` to allow it in a default, I'd consider adding a `warning` along the lines of:

> **Warning**
> A default 'fatalError' will crash your test suite if accessed without being overridden. Consider using a default value instead.

**Comment by stephencelis** [comment]
@jshier `@DependencyClient` adds the exact same test failures but gives them a better name automatically. Also, the default value is _only_ required if the endpoint is non-throwing, so aside from `unimplemented` calling `fatalError` in these cases only, `@DependencyClient` should be the same behavior, but with fewer runtime issues.

**Comment by jshier** [comment]
I guess I'm confused. What do you expect users to do for these defaults? Because you're right, there are no sensible default values for `() -> Int` or `() -> AsyncStream<Int>`, or most other value-returning closures. That's why they were left to be initialized in the first place, so we have to fill them in for the particular environments, where there are meaningful values or test failures. And if the macro is already generating `XCTFail` anyway, when would the return value be used anyway?

**Comment by stephencelis** [comment]
@jshier Don't think about these defaults as "sensible." They are simply there to fulfill the requirement that an unimplemented test should not crash. So you could specify any value, really. The value doesn't matter, as `XCTFail` is called unconditionally before returning it.

You can decide what value makes the most sense for an "unimplemented" dependency endpoint. For authorization status you could return `.notDetermined` or even `.denied`. For a `() -> Float` that is returning the volume you could return `1.0`. For an `AsyncStream<Int>` you could return a stream that completes immediately, etc.
