### ISSUE TITLE
Build error with Xcode 16 beta 6

### ISSUE THREAD

**Issue by theoks** [pointfreeco/swift-dependencies#261]
### Description

Trying to build with Xcode 16 beta 6 and I am getting the following error:

`/swift-dependencies/Sources/Dependencies/WithDependencies.swift:71:51: Returning a task-isolated '@noescape @async @callee_guaranteed @substituted <τ_0_0> () -> (@out τ_0_0, @error any Error) for <R>' value as a 'sending' result risks causing data races`

### Checklist

- [x] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [x] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-dependencies/issues) or [discussion](https://github.com/pointfreeco/swift-dependencies/discussions).

### Dependencies version information

1.3.7

### Destination operating system

iOS 18 beta 7

### Xcode version information

Xcode 16.0 beta 6

**Comment by dafurman** [comment]
For a bit more info, this seems to be new to the 1.3.6 release in particular, as I don't experience this error in 1.3.5.
I can also repro this in Xcode 16.0.0-beta 1, so it doesn't seem specific to a particular beta version.

**Comment by mbrandonw** [comment]
The Xcode betas are a moving target and so everyone must remember that they are using it at their own risk. This issue in particular already came up in a previous beta and was fixed with https://github.com/pointfreeco/swift-dependencies/pull/256, and now a new beta has caused _that_ fix to be a problem. That’s just the reality of using betas. 

Hopefully #262 will fix things for people until the next problem.

**Comment by mbrandonw** [comment]
Hi all, this has been fixed and released in 1.3.8. Going to close this for now, but please do open a discussion if you have questions or discover other problems.
